export const STRIPE_PUB_KEY = process.env.REACT_APP_STRIPE_PUB_KEY
export const ENDPOINT = process.env.REACT_APP_ENDPOINT

export const FONTS = [
    'sistem-ui',
    'Arial',
    'Verdana',
    'Georgia',
    'Times New Roman',
    'Roboto',
    'Tahoma'
]

export const STYLES = [
    'Rounded',
    'Sharp',
    'Pill',
]

export const COUNTRIES = [
    {id: 'AFG', name: "Afghanistan", img: '/static/countries/af.svg'},
    {id: 'ALB', name: "Albania", img: '/static/countries/al.svg'},
    {id: 'DZA', name: "Algeria", img: '/static/countries/dz.svg'},
    {id: 'ASM', name: "American Samoa", img: '/static/countries/as.svg'},
    {id: 'AND', name: "Andorra", img: '/static/countries/ad.svg'},
    {id: 'AGO', name: "Angola", img: '/static/countries/ao.svg'},
    {id: 'AIA', name: "Anguilla", img: '/static/countries/ai.svg'},
    {id: 'ATA', name: "Antarctica", img: '/static/countries/aq.svg'},
    {id: 'ATG', name: "Antigua and Barbuda", img: '/static/countries/ag.svg'},
    {id: 'ARG', name: "Argentina", img: '/static/countries/ar.svg'},
    {id: 'ARM', name: "Armenia", img: '/static/countries/am.svg'},
    {id: 'ABW', name: "Aruba", img: '/static/countries/aw.svg'},
    {id: 'AUS', name: "Australia", img: '/static/countries/au.svg'},
    {id: 'AUT', name: "Austria", img: '/static/countries/at.svg'},
    {id: 'AZE', name: "Azerbaijan", img: '/static/countries/az.svg'},
    {id: 'BHS', name: "Bahamas", img: '/static/countries/bs.svg'},
    {id: 'BHR', name: "Bahrain", img: '/static/countries/bh.svg'},
    {id: 'BGD', name: "Bangladesh", img: '/static/countries/bd.svg'},
    {id: 'BRB', name: "Barbados", img: '/static/countries/bb.svg'},
    {id: 'BLR', name: "Belarus", img: '/static/countries/by.svg'},
    {id: 'BEL', name: "Belgium", img: '/static/countries/be.svg'},
    {id: 'BLZ', name: "Belize", img: '/static/countries/bz.svg'},
    {id: 'BEN', name: "Benin", img: '/static/countries/bj.svg'},
    {id: 'BMU', name: "Bermuda", img: '/static/countries/bm.svg'},
    {id: 'BTN', name: "Bhutan", img: '/static/countries/bt.svg'},
    {id: 'BOL', name: "Bolivia", img: '/static/countries/bo.svg'},
    {id: 'BES', name: "Bonaire, Sint Eustatius and Saba", img: '/static/countries/bq.svg'},
    {id: 'BIH', name: "Bosnia and Herzegovina", img: '/static/countries/ba.svg'},
    {id: 'BWA', name: "Botswana", img: '/static/countries/bw.svg'},
    {id: 'BVT', name: "Bouvet Island", img: '/static/countries/bv.svg'},
    {id: 'BRA', name: "Brazil", img: '/static/countries/br.svg'},
    {id: 'IOT', name: "British Indian Ocean Territory", img: '/static/countries/io.svg'},
    {id: 'BRN', name: "Brunei Darussalam", img: '/static/countries/bn.svg'},
    {id: 'BGR', name: "Bulgaria", img: '/static/countries/bg.svg'},
    {id: 'BFA', name: "Burkina Faso", img: '/static/countries/bf.svg'},
    {id: 'BDI', name: "Burundi", img: '/static/countries/bi.svg'},
    {id: 'CPV', name: "Cabo Verde", img: '/static/countries/cv.svg'},
    {id: 'KHM', name: "Cambodia", img: '/static/countries/kh.svg'},
    {id: 'CMR', name: "Cameroon", img: '/static/countries/cm.svg'},
    {id: 'CAN', name: "Canada", img: '/static/countries/ca.svg'},
    {id: 'CYM', name: "Cayman Islands", img: '/static/countries/ky.svg'},
    {id: 'CAF', name: "Central African Republic", img: '/static/countries/cf.svg'},
    {id: 'TCD', name: "Chad", img: '/static/countries/td.svg'},
    {id: 'CHL', name: "Chile", img: '/static/countries/cl.svg'},
    {id: 'CHN', name: "China", img: '/static/countries/cn.svg'},
    {id: 'CXR', name: "Christmas Island", img: '/static/countries/cx.svg'},
    {id: 'CCK', name: "Cocos Islands", img: '/static/countries/cc.svg'},
    {id: 'COL', name: "Colombia", img: '/static/countries/co.svg'},
    {id: 'COM', name: "Comoros", img: '/static/countries/km.svg'},
    {id: 'COD', name: "Democratic Republic of the Congo", img: '/static/countries/cd.svg'},
    {id: 'COG', name: "Congo", img: '/static/countries/cg.svg'},
    {id: 'COK', name: "Cook Islands", img: '/static/countries/ck.svg'},
    {id: 'CRI', name: "Costa Rica", img: '/static/countries/cr.svg'},
    {id: 'HRV', name: "Croatia", img: '/static/countries/hr.svg'},
    {id: 'CUB', name: "Cuba", img: '/static/countries/cu.svg'},
    {id: 'CUW', name: "Curaçao", img: '/static/countries/cw.svg'},
    {id: 'CYP', name: "Cyprus", img: '/static/countries/cy.svg'},
    {id: 'CZE', name: "Czechia", img: '/static/countries/cz.svg'},
    {id: 'CIV', name: "Côte d'Ivoire", img: '/static/countries/ci.svg'},
    {id: 'DNK', name: "Denmark", img: '/static/countries/dk.svg'},
    {id: 'DJI', name: "Djibouti", img: '/static/countries/dj.svg'},
    {id: 'DMA', name: "Dominica", img: '/static/countries/dm.svg'},
    {id: 'DOM', name: "Dominican Republic", img: '/static/countries/do.svg'},
    {id: 'ECU', name: "Ecuador", img: '/static/countries/ec.svg'},
    {id: 'EGY', name: "Egypt", img: '/static/countries/eg.svg'},
    {id: 'SLV', name: "El Salvador", img: '/static/countries/sv.svg'},
    {id: 'GNQ', name: "Equatorial Guinea", img: '/static/countries/gq.svg'},
    {id: 'ERI', name: "Eritrea", img: '/static/countries/er.svg'},
    {id: 'EST', name: "Estonia", img: '/static/countries/ee.svg'},
    {id: 'SWZ', name: "Eswatini", img: '/static/countries/sz.svg'},
    {id: 'ETH', name: "Ethiopia", img: '/static/countries/et.svg'},
    {id: 'FLK', name: "Falkland Islands", img: '/static/countries/fk.svg'},
    {id: 'FRO', name: "Faroe Islands", img: '/static/countries/fo.svg'},
    {id: 'FJI', name: "Fiji", img: '/static/countries/fj.svg'},
    {id: 'FIN', name: "Finland", img: '/static/countries/fi.svg'},
    {id: 'FRA', name: "France", img: '/static/countries/fr.svg'},
    {id: 'GUF', name: "French Guiana", img: '/static/countries/gf.svg'},
    {id: 'PYF', name: "French Polynesia", img: '/static/countries/pf.svg'},
    {id: 'ATF', name: "French Southern Territories", img: '/static/countries/tf.svg'},
    {id: 'GAB', name: "Gabon", img: '/static/countries/ga.svg'},
    {id: 'GMB', name: "Gambia", img: '/static/countries/gm.svg'},
    {id: 'GEO', name: "Georgia", img: '/static/countries/ge.svg'},
    {id: 'DEU', name: "Germany", img: '/static/countries/de.svg'},
    {id: 'GHA', name: "Ghana", img: '/static/countries/gh.svg'},
    {id: 'GIB', name: "Gibraltar", img: '/static/countries/gi.svg'},
    {id: 'GRC', name: "Greece", img: '/static/countries/gr.svg'},
    {id: 'GRL', name: "Greenland", img: '/static/countries/gl.svg'},
    {id: 'GRD', name: "Grenada", img: '/static/countries/gd.svg'},
    {id: 'GLP', name: "Guadeloupe", img: '/static/countries/gp.svg'},
    {id: 'GUM', name: "Guam", img: '/static/countries/gu.svg'},
    {id: 'GTM', name: "Guatemala", img: '/static/countries/gt.svg'},
    {id: 'GGY', name: "Guernsey", img: '/static/countries/gg.svg'},
    {id: 'GIN', name: "Guinea", img: '/static/countries/gn.svg'},
    {id: 'GNB', name: "Guinea-Bissau", img: '/static/countries/gw.svg'},
    {id: 'GUY', name: "Guyana", img: '/static/countries/gy.svg'},
    {id: 'HTI', name: "Haiti", img: '/static/countries/ht.svg'},
    {id: 'HMD', name: "Heard Island and McDonald Islands", img: '/static/countries/hm.svg'},
    {id: 'VAT', name: "Holy See", img: '/static/countries/va.svg'},
    {id: 'HND', name: "Honduras", img: '/static/countries/hn.svg'},
    {id: 'HKG', name: "Hong Kong", img: '/static/countries/hk.svg'},
    {id: 'HUN', name: "Hungary", img: '/static/countries/hu.svg'},
    {id: 'ISL', name: "Iceland", img: '/static/countries/is.svg'},
    {id: 'IND', name: "India", img: '/static/countries/in.svg'},
    {id: 'IDN', name: "Indonesia", img: '/static/countries/id.svg'},
    {id: 'IRN', name: "Iran", img: '/static/countries/ir.svg'},
    {id: 'IRQ', name: "Iraq", img: '/static/countries/iq.svg'},
    {id: 'IRL', name: "Ireland", img: '/static/countries/ie.svg'},
    {id: 'IMN', name: "Isle of Man", img: '/static/countries/im.svg'},
    {id: 'ISR', name: "Israel", img: '/static/countries/il.svg'},
    {id: 'ITA', name: "Italy", img: '/static/countries/it.svg'},
    {id: 'JAM', name: "Jamaica", img: '/static/countries/jm.svg'},
    {id: 'JPN', name: "Japan", img: '/static/countries/jp.svg'},
    {id: 'JEY', name: "Jersey", img: '/static/countries/je.svg'},
    {id: 'JOR', name: "Jordan", img: '/static/countries/jo.svg'},
    {id: 'KAZ', name: "Kazakhstan", img: '/static/countries/kz.svg'},
    {id: 'KEN', name: "Kenya", img: '/static/countries/ke.svg'},
    {id: 'KIR', name: "Kiribati", img: '/static/countries/ki.svg'},
    {id: 'PRK', name: "North Korea", img: '/static/countries/kp.svg'},
    {id: 'KOR', name: "South Korea", img: '/static/countries/kr.svg'},
    {id: 'KWT', name: "Kuwait", img: '/static/countries/kw.svg'},
    {id: 'KGZ', name: "Kyrgyzstan", img: '/static/countries/kg.svg'},
    {id: 'LAO', name: "Lao People's Democratic Republic", img: '/static/countries/la.svg'},
    {id: 'LVA', name: "Latvia", img: '/static/countries/lv.svg'},
    {id: 'LBN', name: "Lebanon", img: '/static/countries/lb.svg'},
    {id: 'LSO', name: "Lesotho", img: '/static/countries/ls.svg'},
    {id: 'LBR', name: "Liberia", img: '/static/countries/lr.svg'},
    {id: 'LBY', name: "Libya", img: '/static/countries/ly.svg'},
    {id: 'LIE', name: "Liechtenstein", img: '/static/countries/li.svg'},
    {id: 'LTU', name: "Lithuania", img: '/static/countries/lt.svg'},
    {id: 'LUX', name: "Luxembourg", img: '/static/countries/lu.svg'},
    {id: 'MAC', name: "Macao", img: '/static/countries/mo.svg'},
    {id: 'MDG', name: "Madagascar", img: '/static/countries/mg.svg'},
    {id: 'MWI', name: "Malawi", img: '/static/countries/mw.svg'},
    {id: 'MYS', name: "Malaysia", img: '/static/countries/my.svg'},
    {id: 'MDV', name: "Maldives", img: '/static/countries/mv.svg'},
    {id: 'MLI', name: "Mali", img: '/static/countries/ml.svg'},
    {id: 'MLT', name: "Malta", img: '/static/countries/mt.svg'},
    {id: 'MHL', name: "Marshall Islands", img: '/static/countries/mh.svg'},
    {id: 'MTQ', name: "Martinique", img: '/static/countries/mq.svg'},
    {id: 'MRT', name: "Mauritania", img: '/static/countries/mr.svg'},
    {id: 'MUS', name: "Mauritius", img: '/static/countries/mu.svg'},
    {id: 'MYT', name: "Mayotte", img: '/static/countries/yt.svg'},
    {id: 'MEX', name: "Mexico", img: '/static/countries/mx.svg'},
    {id: 'FSM', name: "Micronesia", img: '/static/countries/fm.svg'},
    {id: 'MDA', name: "Moldova", img: '/static/countries/md.svg'},
    {id: 'MCO', name: "Monaco", img: '/static/countries/mc.svg'},
    {id: 'MNG', name: "Mongolia", img: '/static/countries/mn.svg'},
    {id: 'MNE', name: "Montenegro", img: '/static/countries/me.svg'},
    {id: 'MSR', name: "Montserrat", img: '/static/countries/ms.svg'},
    {id: 'MAR', name: "Morocco", img: '/static/countries/ma.svg'},
    {id: 'MOZ', name: "Mozambique", img: '/static/countries/mz.svg'},
    {id: 'MMR', name: "Myanmar", img: '/static/countries/mm.svg'},
    {id: 'NAM', name: "Namibia", img: '/static/countries/na.svg'},
    {id: 'NRU', name: "Nauru", img: '/static/countries/nr.svg'},
    {id: 'NPL', name: "Nepal", img: '/static/countries/np.svg'},
    {id: 'NLD', name: "Netherlands", img: '/static/countries/nl.svg'},
    {id: 'NCL', name: "New Caledonia", img: '/static/countries/nc.svg'},
    {id: 'NZL', name: "New Zealand", img: '/static/countries/nz.svg'},
    {id: 'NIC', name: "Nicaragua", img: '/static/countries/ni.svg'},
    {id: 'NER', name: "Niger", img: '/static/countries/ne.svg'},
    {id: 'NGA', name: "Nigeria", img: '/static/countries/ng.svg'},
    {id: 'NIU', name: "Niue", img: '/static/countries/nu.svg'},
    {id: 'NFK', name: "Norfolk Island", img: '/static/countries/nf.svg'},
    {id: 'MNP', name: "Northern Mariana Islands", img: '/static/countries/mp.svg'},
    {id: 'NOR', name: "Norway", img: '/static/countries/no.svg'},
    {id: 'OMN', name: "Oman", img: '/static/countries/om.svg'},
    {id: 'PAK', name: "Pakistan", img: '/static/countries/pk.svg'},
    {id: 'PLW', name: "Palau", img: '/static/countries/pw.svg'},
    {id: 'PSE', name: "Palestine, State of", img: '/static/countries/ps.svg'},
    {id: 'PAN', name: "Panama", img: '/static/countries/pa.svg'},
    {id: 'PNG', name: "Papua New Guinea", img: '/static/countries/pg.svg'},
    {id: 'PRY', name: "Paraguay", img: '/static/countries/py.svg'},
    {id: 'PER', name: "Peru", img: '/static/countries/pe.svg'},
    {id: 'PHL', name: "Philippines", img: '/static/countries/ph.svg'},
    {id: 'PCN', name: "Pitcairn", img: '/static/countries/pn.svg'},
    {id: 'POL', name: "Poland", img: '/static/countries/pl.svg'},
    {id: 'PRT', name: "Portugal", img: '/static/countries/pt.svg'},
    {id: 'PRI', name: "Puerto Rico", img: '/static/countries/pr.svg'},
    {id: 'QAT', name: "Qatar", img: '/static/countries/qa.svg'},
    {id: 'MKD', name: "Republic of North Macedonia", img: '/static/countries/mk.svg'},
    {id: 'ROU', name: "Romania", img: '/static/countries/ro.svg'},
    {id: 'RUS', name: "Russian Federation", img: '/static/countries/ru.svg'},
    {id: 'RWA', name: "Rwanda", img: '/static/countries/rw.svg'},
    {id: 'REU', name: "Réunion", img: '/static/countries/re.svg'},
    {id: 'BLM', name: "Saint Barthélemy", img: '/static/countries/bl.svg'},
    {id: 'SHN', name: "Saint Helena, Ascension and Tristan da Cunha", img: '/static/countries/sh.svg'},
    {id: 'KNA', name: "Saint Kitts and Nevis", img: '/static/countries/kn.svg'},
    {id: 'LCA', name: "Saint Lucia", img: '/static/countries/lc.svg'},
    {id: 'MAF', name: "Saint Martin", img: '/static/countries/mf.svg'},
    {id: 'SPM', name: "Saint Pierre and Miquelon", img: '/static/countries/pm.svg'},
    {id: 'VCT', name: "Saint Vincent and the Grenadines", img: '/static/countries/vc.svg'},
    {id: 'WSM', name: "Samoa", img: '/static/countries/ws.svg'},
    {id: 'SMR', name: "San Marino", img: '/static/countries/sm.svg'},
    {id: 'STP', name: "Sao Tome and Principe", img: '/static/countries/st.svg'},
    {id: 'SAU', name: "Saudi Arabia", img: '/static/countries/sa.svg'},
    {id: 'SEN', name: "Senegal", img: '/static/countries/sn.svg'},
    {id: 'SRB', name: "Serbia", img: '/static/countries/rs.svg'},
    {id: 'SYC', name: "Seychelles", img: '/static/countries/sc.svg'},
    {id: 'SLE', name: "Sierra Leone", img: '/static/countries/sl.svg'},
    {id: 'SGP', name: "Singapore", img: '/static/countries/sg.svg'},
    {id: 'SXM', name: "Sint Maarten", img: '/static/countries/sx.svg'},
    {id: 'SVK', name: "Slovakia", img: '/static/countries/sk.svg'},
    {id: 'SVN', name: "Slovenia", img: '/static/countries/si.svg'},
    {id: 'SLB', name: "Solomon Islands", img: '/static/countries/sb.svg'},
    {id: 'SOM', name: "Somalia", img: '/static/countries/so.svg'},
    {id: 'ZAF', name: "South Africa", img: '/static/countries/za.svg'},
    {id: 'SGS', name: "South Georgia and the South Sandwich Islands", img: '/static/countries/gs.svg'},
    {id: 'SSD', name: "South Sudan", img: '/static/countries/ss.svg'},
    {id: 'ESP', name: "Spain", img: '/static/countries/es.svg'},
    {id: 'LKA', name: "Sri Lanka", img: '/static/countries/lk.svg'},
    {id: 'SDN', name: "Sudan", img: '/static/countries/sd.svg'},
    {id: 'SUR', name: "Suriname", img: '/static/countries/sr.svg'},
    {id: 'SJM', name: "Svalbard and Jan Mayen", img: '/static/countries/sj.svg'},
    {id: 'SWE', name: "Sweden", img: '/static/countries/se.svg'},
    {id: 'CHE', name: "Switzerland", img: '/static/countries/ch.svg'},
    {id: 'SYR', name: "Syrian Arab Republic", img: '/static/countries/sy.svg'},
    {id: 'TWN', name: "Taiwan", img: '/static/countries/tw.svg'},
    {id: 'TJK', name: "Tajikistan", img: '/static/countries/tj.svg'},
    {id: 'TZA', name: "Tanzania", img: '/static/countries/tz.svg'},
    {id: 'THA', name: "Thailand", img: '/static/countries/th.svg'},
    {id: 'TLS', name: "Timor-Leste", img: '/static/countries/tl.svg'},
    {id: 'TGO', name: "Togo", img: '/static/countries/tg.svg'},
    {id: 'TKL', name: "Tokelau", img: '/static/countries/tk.svg'},
    {id: 'TON', name: "Tonga", img: '/static/countries/to.svg'},
    {id: 'TTO', name: "Trinidad and Tobago", img: '/static/countries/tt.svg'},
    {id: 'TUN', name: "Tunisia", img: '/static/countries/tn.svg'},
    {id: 'TUR', name: "Turkey", img: '/static/countries/tr.svg'},
    {id: 'TKM', name: "Turkmenistan", img: '/static/countries/tm.svg'},
    {id: 'TCA', name: "Turks and Caicos Islands", img: '/static/countries/tc.svg'},
    {id: 'TUV', name: "Tuvalu", img: '/static/countries/tv.svg'},
    {id: 'UGA', name: "Uganda", img: '/static/countries/ug.svg'},
    {id: 'UKR', name: "Ukraine", img: '/static/countries/ua.svg'},
    {id: 'ARE', name: "United Arab Emirates", img: '/static/countries/ae.svg'},
    {id: 'GBR', name: "United Kingdom", img: '/static/countries/gb.svg'},
    // {id: 'UMI', name: "United States Minor Outlying Islands", img: '/static/countries/um.svg'},
    {id: 'USA', name: "United States of America", img: '/static/countries/us.svg'},
    {id: 'URY', name: "Uruguay", img: '/static/countries/uy.svg'},
    {id: 'UZB', name: "Uzbekistan", img: '/static/countries/uz.svg'},
    {id: 'VUT', name: "Vanuatu", img: '/static/countries/vu.svg'},
    {id: 'VEN', name: "Venezuela", img: '/static/countries/ve.svg'},
    {id: 'VNM', name: "Viet Nam", img: '/static/countries/vn.svg'},
    {id: 'VGB', name: "Virgin Islands (British)", img: '/static/countries/vg.svg'},
    {id: 'VIR', name: "Virgin Islands (U.S.)", img: '/static/countries/vi.svg'},
    {id: 'WLF', name: "Wallis and Futuna", img: '/static/countries/wf.svg'},
    {id: 'ESH', name: "Western Sahara", img: '/static/countries/eh.svg'},
    {id: 'YEM', name: "Yemen", img: '/static/countries/ye.svg'},
    {id: 'ZMB', name: "Zambia", img: '/static/countries/zm.svg'},
    {id: 'ZWE', name: "Zimbabwe", img: '/static/countries/zw.svg'},
    {id: 'ALA', name: "Åland Islands", img: '/static/countries/ax.svg'},
]