export const ENDPOINT = process.env.REACT_APP_ENDPOINT
export const DEMO_LINK = process.env.REACT_APP_DEMO_LINK
export const DEMO_PROMPT_ID = process.env.REACT_APP_DEMO_PROMPT_ID

export const FONTS = [
    'sistem-ui',
    'Arial',
    'Verdana',
    'Georgia',
    'Times New Roman',
    'Roboto',
    'Tahoma'
]

export const STYLES = [
    'Rounded',
    'Sharp',
    'Pill',
]

export const COUNTRIES = [
    {id: 'AFG', alpha2: "AF", name: "Afghanistan", img: '/static/countries/af.svg'},
    {id: 'ALB', alpha2: "AL", name: "Albania", img: '/static/countries/al.svg'},
    {id: 'DZA', alpha2: "DZ", name: "Algeria", img: '/static/countries/dz.svg'},
    {id: 'ASM', alpha2: "AS", name: "American Samoa", img: '/static/countries/as.svg'},
    {id: 'AND', alpha2: "AD", name: "Andorra", img: '/static/countries/ad.svg'},
    {id: 'AGO', alpha2: "AO", name: "Angola", img: '/static/countries/ao.svg'},
    {id: 'AIA', alpha2: "AI", name: "Anguilla", img: '/static/countries/ai.svg'},
    {id: 'ATA', alpha2: "AQ", name: "Antarctica", img: '/static/countries/aq.svg'},
    {id: 'ATG', alpha2: "AG", name: "Antigua and Barbuda", img: '/static/countries/ag.svg'},
    {id: 'ARG', alpha2: "AR", name: "Argentina", img: '/static/countries/ar.svg'},
    {id: 'ARM', alpha2: "AM", name: "Armenia", img: '/static/countries/am.svg'},
    {id: 'ABW', alpha2: "AW", name: "Aruba", img: '/static/countries/aw.svg'},
    {id: 'AUS', alpha2: "AU", name: "Australia", img: '/static/countries/au.svg'},
    {id: 'AUT', alpha2: "AT", name: "Austria", img: '/static/countries/at.svg'},
    {id: 'AZE', alpha2: "AZ", name: "Azerbaijan", img: '/static/countries/az.svg'},
    {id: 'BHS', alpha2: "BS", name: "Bahamas", img: '/static/countries/bs.svg'},
    {id: 'BHR', alpha2: "BH", name: "Bahrain", img: '/static/countries/bh.svg'},
    {id: 'BGD', alpha2: "BD", name: "Bangladesh", img: '/static/countries/bd.svg'},
    {id: 'BRB', alpha2: "BB", name: "Barbados", img: '/static/countries/bb.svg'},
    {id: 'BLR', alpha2: "BY", name: "Belarus", img: '/static/countries/by.svg'},
    {id: 'BEL', alpha2: "BE", name: "Belgium", img: '/static/countries/be.svg'},
    {id: 'BLZ', alpha2: "BZ", name: "Belize", img: '/static/countries/bz.svg'},
    {id: 'BEN', alpha2: "BJ", name: "Benin", img: '/static/countries/bj.svg'},
    {id: 'BMU', alpha2: "BM", name: "Bermuda", img: '/static/countries/bm.svg'},
    {id: 'BTN', alpha2: "BT", name: "Bhutan", img: '/static/countries/bt.svg'},
    {id: 'BOL', alpha2: "BO", name: "Bolivia", img: '/static/countries/bo.svg'},
    {id: 'BES', alpha2: "BQ", name: "Bonaire, Sint Eustatius and Saba", img: '/static/countries/bq.svg'},
    {id: 'BIH', alpha2: "BA", name: "Bosnia and Herzegovina", img: '/static/countries/ba.svg'},
    {id: 'BWA', alpha2: "BW", name: "Botswana", img: '/static/countries/bw.svg'},
    {id: 'BVT', alpha2: "BV", name: "Bouvet Island", img: '/static/countries/bv.svg'},
    {id: 'BRA', alpha2: "BR", name: "Brazil", img: '/static/countries/br.svg'},
    {id: 'IOT', alpha2: "IO", name: "British Indian Ocean Territory", img: '/static/countries/io.svg'},
    {id: 'BRN', alpha2: "BN", name: "Brunei Darussalam", img: '/static/countries/bn.svg'},
    {id: 'BGR', alpha2: "BG", name: "Bulgaria", img: '/static/countries/bg.svg'},
    {id: 'BFA', alpha2: "BF", name: "Burkina Faso", img: '/static/countries/bf.svg'},
    {id: 'BDI', alpha2: "BI", name: "Burundi", img: '/static/countries/bi.svg'},
    {id: 'CPV', alpha2: "CV", name: "Cabo Verde", img: '/static/countries/cv.svg'},
    {id: 'KHM', alpha2: "KH", name: "Cambodia", img: '/static/countries/kh.svg'},
    {id: 'CMR', alpha2: "CM", name: "Cameroon", img: '/static/countries/cm.svg'},
    {id: 'CAN', alpha2: "CA", name: "Canada", img: '/static/countries/ca.svg'},
    {id: 'CYM', alpha2: "KY", name: "Cayman Islands", img: '/static/countries/ky.svg'},
    {id: 'CAF', alpha2: "CF", name: "Central African Republic", img: '/static/countries/cf.svg'},
    {id: 'TCD', alpha2: "TD", name: "Chad", img: '/static/countries/td.svg'},
    {id: 'CHL', alpha2: "CL", name: "Chile", img: '/static/countries/cl.svg'},
    {id: 'CHN', alpha2: "CN", name: "China", img: '/static/countries/cn.svg'},
    {id: 'CXR', alpha2: "CX", name: "Christmas Island", img: '/static/countries/cx.svg'},
    {id: 'CCK', alpha2: "CC", name: "Cocos Islands", img: '/static/countries/cc.svg'},
    {id: 'COL', alpha2: "CO", name: "Colombia", img: '/static/countries/co.svg'},
    {id: 'COM', alpha2: "KM", name: "Comoros", img: '/static/countries/km.svg'},
    {id: 'COD', alpha2: "CD", name: "Democratic Republic of the Congo", img: '/static/countries/cd.svg'},
    {id: 'COG', alpha2: "CG", name: "Congo", img: '/static/countries/cg.svg'},
    {id: 'COK', alpha2: "CK", name: "Cook Islands", img: '/static/countries/ck.svg'},
    {id: 'CRI', alpha2: "CR", name: "Costa Rica", img: '/static/countries/cr.svg'},
    {id: 'HRV', alpha2: "HR", name: "Croatia", img: '/static/countries/hr.svg'},
    {id: 'CUB', alpha2: "CU", name: "Cuba", img: '/static/countries/cu.svg'},
    {id: 'CUW', alpha2: "CW", name: "Curaçao", img: '/static/countries/cw.svg'},
    {id: 'CYP', alpha2: "CY", name: "Cyprus", img: '/static/countries/cy.svg'},
    {id: 'CZE', alpha2: "CZ", name: "Czechia", img: '/static/countries/cz.svg'},
    {id: 'CIV', alpha2: "CI", name: "Côte d'Ivoire", img: '/static/countries/ci.svg'},
    {id: 'DNK', alpha2: "DK", name: "Denmark", img: '/static/countries/dk.svg'},
    {id: 'DJI', alpha2: "DJ", name: "Djibouti", img: '/static/countries/dj.svg'},
    {id: 'DMA', alpha2: "DM", name: "Dominica", img: '/static/countries/dm.svg'},
    {id: 'DOM', alpha2: "DO", name: "Dominican Republic", img: '/static/countries/do.svg'},
    {id: 'ECU', alpha2: "EC", name: "Ecuador", img: '/static/countries/ec.svg'},
    {id: 'EGY', alpha2: "EG", name: "Egypt", img: '/static/countries/eg.svg'},
    {id: 'SLV', alpha2: "SV", name: "El Salvador", img: '/static/countries/sv.svg'},
    {id: 'GNQ', alpha2: "GQ", name: "Equatorial Guinea", img: '/static/countries/gq.svg'},
    {id: 'ERI', alpha2: "ER", name: "Eritrea", img: '/static/countries/er.svg'},
    {id: 'EST', alpha2: "EE", name: "Estonia", img: '/static/countries/ee.svg'},
    {id: 'SWZ', alpha2: "SZ", name: "Eswatini", img: '/static/countries/sz.svg'},
    {id: 'ETH', alpha2: "ET", name: "Ethiopia", img: '/static/countries/et.svg'},
    {id: 'FLK', alpha2: "FK", name: "Falkland Islands", img: '/static/countries/fk.svg'},
    {id: 'FRO', alpha2: "FO", name: "Faroe Islands", img: '/static/countries/fo.svg'},
    {id: 'FJI', alpha2: "FJ", name: "Fiji", img: '/static/countries/fj.svg'},
    {id: 'FIN', alpha2: "FI", name: "Finland", img: '/static/countries/fi.svg'},
    {id: 'FRA', alpha2: "FR", name: "France", img: '/static/countries/fr.svg'},
    {id: 'GUF', alpha2: "GF", name: "French Guiana", img: '/static/countries/gf.svg'},
    {id: 'PYF', alpha2: "PF", name: "French Polynesia", img: '/static/countries/pf.svg'},
    {id: 'ATF', alpha2: "TF", name: "French Southern Territories", img: '/static/countries/tf.svg'},
    {id: 'GAB', alpha2: "GA", name: "Gabon", img: '/static/countries/ga.svg'},
    {id: 'GMB', alpha2: "GM", name: "Gambia", img: '/static/countries/gm.svg'},
    {id: 'GEO', alpha2: "GE", name: "Georgia", img: '/static/countries/ge.svg'},
    {id: 'DEU', alpha2: "DE", name: "Germany", img: '/static/countries/de.svg'},
    {id: 'GHA', alpha2: "GH", name: "Ghana", img: '/static/countries/gh.svg'},
    {id: 'GIB', alpha2: "GI", name: "Gibraltar", img: '/static/countries/gi.svg'},
    {id: 'GRC', alpha2: "GR", name: "Greece", img: '/static/countries/gr.svg'},
    {id: 'GRL', alpha2: "GL", name: "Greenland", img: '/static/countries/gl.svg'},
    {id: 'GRD', alpha2: "GD", name: "Grenada", img: '/static/countries/gd.svg'},
    {id: 'GLP', alpha2: "GP", name: "Guadeloupe", img: '/static/countries/gp.svg'},
    {id: 'GUM', alpha2: "GU", name: "Guam", img: '/static/countries/gu.svg'},
    {id: 'GTM', alpha2: "GT", name: "Guatemala", img: '/static/countries/gt.svg'},
    {id: 'GGY', alpha2: "GG", name: "Guernsey", img: '/static/countries/gg.svg'},
    {id: 'GIN', alpha2: "GN", name: "Guinea", img: '/static/countries/gn.svg'},
    {id: 'GNB', alpha2: "GW", name: "Guinea-Bissau", img: '/static/countries/gw.svg'},
    {id: 'GUY', alpha2: "GY", name: "Guyana", img: '/static/countries/gy.svg'},
    {id: 'HTI', alpha2: "HT", name: "Haiti", img: '/static/countries/ht.svg'},
    {id: 'HMD', alpha2: "HM", name: "Heard Island and McDonald Islands", img: '/static/countries/hm.svg'},
    {id: 'VAT', alpha2: "VA", name: "Holy See", img: '/static/countries/va.svg'},
    {id: 'HND', alpha2: "HN", name: "Honduras", img: '/static/countries/hn.svg'},
    {id: 'HKG', alpha2: "HK", name: "Hong Kong", img: '/static/countries/hk.svg'},
    {id: 'HUN', alpha2: "HU", name: "Hungary", img: '/static/countries/hu.svg'},
    {id: 'ISL', alpha2: "IS", name: "Iceland", img: '/static/countries/is.svg'},
    {id: 'IND', alpha2: "IN", name: "India", img: '/static/countries/in.svg'},
    {id: 'IDN', alpha2: "ID", name: "Indonesia", img: '/static/countries/id.svg'},
    {id: 'IRN', alpha2: "IR", name: "Iran", img: '/static/countries/ir.svg'},
    {id: 'IRQ', alpha2: "IQ", name: "Iraq", img: '/static/countries/iq.svg'},
    {id: 'IRL', alpha2: "IE", name: "Ireland", img: '/static/countries/ie.svg'},
    {id: 'IMN', alpha2: "IM", name: "Isle of Man", img: '/static/countries/im.svg'},
    {id: 'ISR', alpha2: "IL", name: "Israel", img: '/static/countries/il.svg'},
    {id: 'ITA', alpha2: "IT", name: "Italy", img: '/static/countries/it.svg'},
    {id: 'JAM', alpha2: "JM", name: "Jamaica", img: '/static/countries/jm.svg'},
    {id: 'JPN', alpha2: "JP", name: "Japan", img: '/static/countries/jp.svg'},
    {id: 'JEY', alpha2: "JE", name: "Jersey", img: '/static/countries/je.svg'},
    {id: 'JOR', alpha2: "JO", name: "Jordan", img: '/static/countries/jo.svg'},
    {id: 'KAZ', alpha2: "KZ", name: "Kazakhstan", img: '/static/countries/kz.svg'},
    {id: 'KEN', alpha2: "KE", name: "Kenya", img: '/static/countries/ke.svg'},
    {id: 'KIR', alpha2: "KI", name: "Kiribati", img: '/static/countries/ki.svg'},
    {id: 'PRK', alpha2: "KP", name: "North Korea", img: '/static/countries/kp.svg'},
    {id: 'KOR', alpha2: "KR", name: "South Korea", img: '/static/countries/kr.svg'},
    {id: 'KWT', alpha2: "KW", name: "Kuwait", img: '/static/countries/kw.svg'},
    {id: 'KGZ', alpha2: "KG", name: "Kyrgyzstan", img: '/static/countries/kg.svg'},
    {id: 'LAO', alpha2: "LA", name: "Lao People's Democratic Republic", img: '/static/countries/la.svg'},
    {id: 'LVA', alpha2: "LV", name: "Latvia", img: '/static/countries/lv.svg'},
    {id: 'LBN', alpha2: "LB", name: "Lebanon", img: '/static/countries/lb.svg'},
    {id: 'LSO', alpha2: "LS", name: "Lesotho", img: '/static/countries/ls.svg'},
    {id: 'LBR', alpha2: "LR", name: "Liberia", img: '/static/countries/lr.svg'},
    {id: 'LBY', alpha2: "LY", name: "Libya", img: '/static/countries/ly.svg'},
    {id: 'LIE', alpha2: "LI", name: "Liechtenstein", img: '/static/countries/li.svg'},
    {id: 'LTU', alpha2: "LT", name: "Lithuania", img: '/static/countries/lt.svg'},
    {id: 'LUX', alpha2: "LU", name: "Luxembourg", img: '/static/countries/lu.svg'},
    {id: 'MAC', alpha2: "MO", name: "Macao", img: '/static/countries/mo.svg'},
    {id: 'MDG', alpha2: "MG", name: "Madagascar", img: '/static/countries/mg.svg'},
    {id: 'MWI', alpha2: "MW", name: "Malawi", img: '/static/countries/mw.svg'},
    {id: 'MYS', alpha2: "MY", name: "Malaysia", img: '/static/countries/my.svg'},
    {id: 'MDV', alpha2: "MV", name: "Maldives", img: '/static/countries/mv.svg'},
    {id: 'MLI', alpha2: "ML", name: "Mali", img: '/static/countries/ml.svg'},
    {id: 'MLT', alpha2: "MT", name: "Malta", img: '/static/countries/mt.svg'},
    {id: 'MHL', alpha2: "MH", name: "Marshall Islands", img: '/static/countries/mh.svg'},
    {id: 'MTQ', alpha2: "MQ", name: "Martinique", img: '/static/countries/mq.svg'},
    {id: 'MRT', alpha2: "MR", name: "Mauritania", img: '/static/countries/mr.svg'},
    {id: 'MUS', alpha2: "MU", name: "Mauritius", img: '/static/countries/mu.svg'},
    {id: 'MYT', alpha2: "YT", name: "Mayotte", img: '/static/countries/yt.svg'},
    {id: 'MEX', alpha2: "MX", name: "Mexico", img: '/static/countries/mx.svg'},
    {id: 'FSM', alpha2: "FM", name: "Micronesia", img: '/static/countries/fm.svg'},
    {id: 'MDA', alpha2: "MD", name: "Moldova", img: '/static/countries/md.svg'},
    {id: 'MCO', alpha2: "MC", name: "Monaco", img: '/static/countries/mc.svg'},
    {id: 'MNG', alpha2: "MN", name: "Mongolia", img: '/static/countries/mn.svg'},
    {id: 'MNE', alpha2: "ME", name: "Montenegro", img: '/static/countries/me.svg'},
    {id: 'MSR', alpha2: "MS", name: "Montserrat", img: '/static/countries/ms.svg'},
    {id: 'MAR', alpha2: "MA", name: "Morocco", img: '/static/countries/ma.svg'},
    {id: 'MOZ', alpha2: "MZ", name: "Mozambique", img: '/static/countries/mz.svg'},
    {id: 'MMR', alpha2: "MM", name: "Myanmar", img: '/static/countries/mm.svg'},
    {id: 'NAM', alpha2: "NA", name: "Namibia", img: '/static/countries/na.svg'},
    {id: 'NRU', alpha2: "NR", name: "Nauru", img: '/static/countries/nr.svg'},
    {id: 'NPL', alpha2: "NP", name: "Nepal", img: '/static/countries/np.svg'},
    {id: 'NLD', alpha2: "NL", name: "Netherlands", img: '/static/countries/nl.svg'},
    {id: 'NCL', alpha2: "NC", name: "New Caledonia", img: '/static/countries/nc.svg'},
    {id: 'NZL', alpha2: "NZ", name: "New Zealand", img: '/static/countries/nz.svg'},
    {id: 'NIC', alpha2: "NI", name: "Nicaragua", img: '/static/countries/ni.svg'},
    {id: 'NER', alpha2: "NE", name: "Niger", img: '/static/countries/ne.svg'},
    {id: 'NGA', alpha2: "NG", name: "Nigeria", img: '/static/countries/ng.svg'},
    {id: 'NIU', alpha2: "NU", name: "Niue", img: '/static/countries/nu.svg'},
    {id: 'NFK', alpha2: "NF", name: "Norfolk Island", img: '/static/countries/nf.svg'},
    {id: 'MNP', alpha2: "MP", name: "Northern Mariana Islands", img: '/static/countries/mp.svg'},
    {id: 'NOR', alpha2: "NO", name: "Norway", img: '/static/countries/no.svg'},
    {id: 'OMN', alpha2: "OM", name: "Oman", img: '/static/countries/om.svg'},
    {id: 'PAK', alpha2: "PK", name: "Pakistan", img: '/static/countries/pk.svg'},
    {id: 'PLW', alpha2: "PW", name: "Palau", img: '/static/countries/pw.svg'},
    {id: 'PSE', alpha2: "PS", name: "Palestine, State of", img: '/static/countries/ps.svg'},
    {id: 'PAN', alpha2: "PA", name: "Panama", img: '/static/countries/pa.svg'},
    {id: 'PNG', alpha2: "PG", name: "Papua New Guinea", img: '/static/countries/pg.svg'},
    {id: 'PRY', alpha2: "PY", name: "Paraguay", img: '/static/countries/py.svg'},
    {id: 'PER', alpha2: "PE", name: "Peru", img: '/static/countries/pe.svg'},
    {id: 'PHL', alpha2: "PH", name: "Philippines", img: '/static/countries/ph.svg'},
    {id: 'PCN', alpha2: "PN", name: "Pitcairn", img: '/static/countries/pn.svg'},
    {id: 'POL', alpha2: "PL", name: "Poland", img: '/static/countries/pl.svg'},
    {id: 'PRT', alpha2: "PT", name: "Portugal", img: '/static/countries/pt.svg'},
    {id: 'PRI', alpha2: "PR", name: "Puerto Rico", img: '/static/countries/pr.svg'},
    {id: 'QAT', alpha2: "QA", name: "Qatar", img: '/static/countries/qa.svg'},
    {id: 'MKD', alpha2: "MK", name: "Republic of North Macedonia", img: '/static/countries/mk.svg'},
    {id: 'ROU', alpha2: "RO", name: "Romania", img: '/static/countries/ro.svg'},
    {id: 'RUS', alpha2: "RU", name: "Russian Federation", img: '/static/countries/ru.svg'},
    {id: 'RWA', alpha2: "RW", name: "Rwanda", img: '/static/countries/rw.svg'},
    {id: 'REU', alpha2: "RE", name: "Réunion", img: '/static/countries/re.svg'},
    {id: 'BLM', alpha2: "BL", name: "Saint Barthélemy", img: '/static/countries/bl.svg'},
    {id: 'SHN', alpha2: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", img: '/static/countries/sh.svg'},
    {id: 'KNA', alpha2: "KN", name: "Saint Kitts and Nevis", img: '/static/countries/kn.svg'},
    {id: 'LCA', alpha2: "LC", name: "Saint Lucia", img: '/static/countries/lc.svg'},
    {id: 'MAF', alpha2: "MF", name: "Saint Martin", img: '/static/countries/mf.svg'},
    {id: 'SPM', alpha2: "PM", name: "Saint Pierre and Miquelon", img: '/static/countries/pm.svg'},
    {id: 'VCT', alpha2: "VC", name: "Saint Vincent and the Grenadines", img: '/static/countries/vc.svg'},
    {id: 'WSM', alpha2: "WS", name: "Samoa", img: '/static/countries/ws.svg'},
    {id: 'SMR', alpha2: "SM", name: "San Marino", img: '/static/countries/sm.svg'},
    {id: 'STP', alpha2: "ST", name: "Sao Tome and Principe", img: '/static/countries/st.svg'},
    {id: 'SAU', alpha2: "SA", name: "Saudi Arabia", img: '/static/countries/sa.svg'},
    {id: 'SEN', alpha2: "SN", name: "Senegal", img: '/static/countries/sn.svg'},
    {id: 'SRB', alpha2: "RS", name: "Serbia", img: '/static/countries/rs.svg'},
    {id: 'SYC', alpha2: "SC", name: "Seychelles", img: '/static/countries/sc.svg'},
    {id: 'SLE', alpha2: "SL", name: "Sierra Leone", img: '/static/countries/sl.svg'},
    {id: 'SGP', alpha2: "SG", name: "Singapore", img: '/static/countries/sg.svg'},
    {id: 'SXM', alpha2: "SX", name: "Sint Maarten", img: '/static/countries/sx.svg'},
    {id: 'SVK', alpha2: "SK", name: "Slovakia", img: '/static/countries/sk.svg'},
    {id: 'SVN', alpha2: "SI", name: "Slovenia", img: '/static/countries/si.svg'},
    {id: 'SLB', alpha2: "SB", name: "Solomon Islands", img: '/static/countries/sb.svg'},
    {id: 'SOM', alpha2: "SO", name: "Somalia", img: '/static/countries/so.svg'},
    {id: 'ZAF', alpha2: "ZA", name: "South Africa", img: '/static/countries/za.svg'},
    {id: 'SGS', alpha2: "GS", name: "South Georgia and the South Sandwich Islands", img: '/static/countries/gs.svg'},
    {id: 'SSD', alpha2: "SS", name: "South Sudan", img: '/static/countries/ss.svg'},
    {id: 'ESP', alpha2: "ES", name: "Spain", img: '/static/countries/es.svg'},
    {id: 'LKA', alpha2: "LK", name: "Sri Lanka", img: '/static/countries/lk.svg'},
    {id: 'SDN', alpha2: "SD", name: "Sudan", img: '/static/countries/sd.svg'},
    {id: 'SUR', alpha2: "SR", name: "Suriname", img: '/static/countries/sr.svg'},
    {id: 'SJM', alpha2: "SJ", name: "Svalbard and Jan Mayen", img: '/static/countries/sj.svg'},
    {id: 'SWE', alpha2: "SE", name: "Sweden", img: '/static/countries/se.svg'},
    {id: 'CHE', alpha2: "CH", name: "Switzerland", img: '/static/countries/ch.svg'},
    {id: 'SYR', alpha2: "SY", name: "Syrian Arab Republic", img: '/static/countries/sy.svg'},
    {id: 'TWN', alpha2: "TW", name: "Taiwan", img: '/static/countries/tw.svg'},
    {id: 'TJK', alpha2: "TJ", name: "Tajikistan", img: '/static/countries/tj.svg'},
    {id: 'TZA', alpha2: "TZ", name: "Tanzania", img: '/static/countries/tz.svg'},
    {id: 'THA', alpha2: "TH", name: "Thailand", img: '/static/countries/th.svg'},
    {id: 'TLS', alpha2: "TL", name: "Timor-Leste", img: '/static/countries/tl.svg'},
    {id: 'TGO', alpha2: "TG", name: "Togo", img: '/static/countries/tg.svg'},
    {id: 'TKL', alpha2: "TK", name: "Tokelau", img: '/static/countries/tk.svg'},
    {id: 'TON', alpha2: "TO", name: "Tonga", img: '/static/countries/to.svg'},
    {id: 'TTO', alpha2: "TT", name: "Trinidad and Tobago", img: '/static/countries/tt.svg'},
    {id: 'TUN', alpha2: "TN", name: "Tunisia", img: '/static/countries/tn.svg'},
    {id: 'TUR', alpha2: "TR", name: "Turkey", img: '/static/countries/tr.svg'},
    {id: 'TKM', alpha2: "TM", name: "Turkmenistan", img: '/static/countries/tm.svg'},
    {id: 'TCA', alpha2: "TC", name: "Turks and Caicos Islands", img: '/static/countries/tc.svg'},
    {id: 'TUV', alpha2: "TV", name: "Tuvalu", img: '/static/countries/tv.svg'},
    {id: 'UGA', alpha2: "UG", name: "Uganda", img: '/static/countries/ug.svg'},
    {id: 'UKR', alpha2: "UA", name: "Ukraine", img: '/static/countries/ua.svg'},
    {id: 'ARE', alpha2: "AE", name: "United Arab Emirates", img: '/static/countries/ae.svg'},
    {id: 'GBR', alpha2: "GB", name: "United Kingdom", img: '/static/countries/gb.svg'},
    // {id: 'UMI'alpha2: "UM", , name: "United States Minor Outlying Islands", img: '/static/countries/um.svg'},
    {id: 'USA', alpha2: "US", name: "United States of America", img: '/static/countries/us.svg'},
    {id: 'URY', alpha2: "UY", name: "Uruguay", img: '/static/countries/uy.svg'},
    {id: 'UZB', alpha2: "UZ", name: "Uzbekistan", img: '/static/countries/uz.svg'},
    {id: 'VUT', alpha2: "VU", name: "Vanuatu", img: '/static/countries/vu.svg'},
    {id: 'VEN', alpha2: "VE", name: "Venezuela", img: '/static/countries/ve.svg'},
    {id: 'VNM', alpha2: "VN", name: "Viet Nam", img: '/static/countries/vn.svg'},
    {id: 'VGB', alpha2: "VG", name: "Virgin Islands (British)", img: '/static/countries/vg.svg'},
    {id: 'VIR', alpha2: "VI", name: "Virgin Islands (U.S.)", img: '/static/countries/vi.svg'},
    {id: 'WLF', alpha2: "WF", name: "Wallis and Futuna", img: '/static/countries/wf.svg'},
    {id: 'ESH', alpha2: "EH", name: "Western Sahara", img: '/static/countries/eh.svg'},
    {id: 'YEM', alpha2: "YE", name: "Yemen", img: '/static/countries/ye.svg'},
    {id: 'ZMB', alpha2: "ZM", name: "Zambia", img: '/static/countries/zm.svg'},
    {id: 'ZWE', alpha2: "ZW", name: "Zimbabwe", img: '/static/countries/zw.svg'},
    {id: 'ALA', alpha2: "AX", name: "Åland Islands", img: '/static/countries/ax.svg'},
]